spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:dummy}
    username: ${DB_USERNAME:dummy}
    password: ${DB_PASSWORD:dummy}

mybatis:
  config-location: classpath:mybatis-config.xml

#server:
#  servlet:
#    context-path: /test
